module.exports = {
    HANDS_MAX_CNT: 6,

    ATTRIBUTE_TYPE_PHYSICAL: 0,
    ATTRIBUTE_TYPE_FIRE: 1,
    ATTRIBUTE_TYPE_FROST: 2,
    ATTRIBUTE_TYPE_NATURE: 3,
    ATTRIBUTE_TYPE_SHADOW: 4,
    ATTRIBUTE_TYPE_HOLY: 5,

    CARD_TYPE_PASSIVE: 0,
    CARD_TYPE_ACTIVE: 1,
    CARD_TYPE_INSTANCE: 2,

    ACTIVE_SKILL_NONE: -1,

    TARGET_SELF : 0,
    TARGET_ORDER_AGGRO : 1,
    TARGET_AOE_ROOM : 2,
    TARGET_AOE_COMBAT_TARGETS : 3,

    INPUT_STATE_NORMAL : 0,
    INPUT_STATE_TERMINAL_PASSWORD : 1,

    ROOM_ID_INVALID : 0,
    OWNER_INVALID : 0,

    // 방 아이템 상태
    ROOM_ITEM_STATE_NOT_YET_GEN : 0,
    ROOM_ITEM_STATE_GEN: 1,

    //아이템 부패 상태
    ITEM_DECOMPOSITION_STATE : 0,

    //액션 이벤트
    ACTION_EVENT_ENTER_ROOM : "enterRoom",
    ACTION_EVENT_PICK_ITEM : "pickItem",

};
