module.exports = {
    HANDS_MAX_CNT: 6,

    DAMAGE_TYPE_PHYSICAL: 0,
    DAMAGE_TYPE_FIRE: 1,
    DAMAGE_TYPE_FROST: 2,
    DAMAGE_TYPE_NATURE: 3,
    DAMAGE_TYPE_SHADOW: 4,
    DAMAGE_TYPE_HOLY: 5,

    CARD_TYPE_PASSIVE: 0,
    CARD_TYPE_ACTIVE: 1,
    CARD_TYPE_INSTANCE: 2,
};
