module.exports = {
    HANDS_MAX_CNT: 6,

    ATTRIBUTE_TYPE_PHYSICAL: 0,
    ATTRIBUTE_TYPE_FIRE: 1,
    ATTRIBUTE_TYPE_FROST: 2,
    ATTRIBUTE_TYPE_NATURE: 3,
    ATTRIBUTE_TYPE_SHADOW: 4,
    ATTRIBUTE_TYPE_HOLY: 5,

    CARD_TYPE_PASSIVE: 0,
    CARD_TYPE_ACTIVE: 1,
    CARD_TYPE_INSTANCE: 2,

    ACTIVE_SKILL_NONE: -1,

    TARGET_SELF : 0,
    TARGET_ORDER_AGGRO : 1,
    TARGET_AOE_ROOM : 2,
    TARGET_AOE_COMBAT_TARGETS : 3,
};
