var constants = require('./constants.js');

module.exports = {
    "attack_normal": {
        "displayName": "평타공격",
        "type": constants.CARD_TYPE_ACTIVE,
        "attribute": constants.ATTRIBUTE_TYPE_PHYSICAL,
        "rageSpend": 0,
        "rageGain": 0,
        "factor": 1,
    },
    "attack_physical": {
        "displayName": "물리공격",
        "type": constants.CARD_TYPE_ACTIVE,
        "attribute": constants.ATTRIBUTE_TYPE_PHYSICAL,
        "rageSpend": 10,
        "rageGain": 0,
        "factor": 1,
    },
    "attack_fire": {
        "displayName": "화염공격",
        "type": constants.CARD_TYPE_ACTIVE,
        "attribute": constants.ATTRIBUTE_TYPE_FIRE,
        "rageSpend": 10,
        "rageGain": 0,
        "factor": 1,
    },
    "attack_frost": {
        "displayName": "냉기공격",
        "type": constants.CARD_TYPE_ACTIVE,
        "attribute": constants.ATTRIBUTE_TYPE_FROST,
        "rageSpend": 10,
        "rageGain": 0,
        "factor": 1,
    },
    "attack_nature": {
        "displayName": "자연공격",
        "type": constants.CARD_TYPE_ACTIVE,
        "attribute": constants.ATTRIBUTE_TYPE_NATURE,
        "rageSpend": 10,
        "rageGain": 0,
        "factor": 1,
    },
    "attack_shadow": {
        "displayName": "암흑공격",
        "type": constants.CARD_TYPE_ACTIVE,
        "attribute": constants.ATTRIBUTE_TYPE_SHADOW,
        "rageSpend": 10,
        "rageGain": 0,
        "factor": 1,
    },
    "attack_holy": {
        "displayName": "신성공격",
        "type": constants.CARD_TYPE_ACTIVE,
        "attribute": constants.ATTRIBUTE_TYPE_HOLY,
        "rageSpend": 10,
        "rageGain": 0,
        "factor": 1,
    },
};
